AWSTemplateFormatVersion: '2010-09-09'
Description: The AWS CloudFormation template for wallet

Resources:
  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.medium
      ImageId: ami-00399ec92321828f5
      KeyName: aleph
      SubnetId:
        Fn::ImportValue: prod-public-subnet1-id
      SecurityGroupIds:
        - Fn::ImportValue: prod-bastion-security-group-id
      Tags:
        - Key: Name
          Value: prod-bastion
