---
name: Automatic upstream merge

on:
  # run on 7th and 21th day of any month, ie fortnightly
  schedule:
    - cron: '1 0 7,21 * *'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  main:
    name: Merge polkadot-js/apps
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Merge upstream repo
        uses: Cardinal-Cryptography/github-actions/test-upstream-merge@v6
        with:
          target-repo: Cardinal-Cryptography/azero-dev
          target-branch: alephzero
          upstream-repo-url: https://github.com/polkadot-js/apps
          upstream-branch: master
          slack-webhook-url: ${{ secrets.SLACK_INCOMING_WEBHOOK_TEAM_FRONTEND }}
          git-commit-author: ${{ secrets.AUTOCOMMIT_AUTHOR }}
          git-commit-email: ${{ secrets.AUTOCOMMIT_EMAIL }}
          gh-ci-token: ${{ secrets.CI_GH_TOKEN }}
